// file for making requests to endpoints

// GET all books in array
GET http://localhost:3000/api/books/aa21cdd0-0746-11ec-bf41-81ca6e9c50dd
###

// Post new book with name and number of pages to array
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "name": "testar",
    "pages": 50
}

###

// Post with empty body to test how response it
POST http://localhost:3000/api/books
Content-Type: application/json

{
   
}

###

// Update "Book" by its id
PUT http://localhost:3000/api/books/751aab70-0746-11ec-b390-e39af917d79e
Content-Type: application/json

{
    "name": "Test",
    "pages": 500
}

###

// Deletes one "Book" from array by its id
DELETE http://localhost:3000/api/books/e5941320-0744-11ec-ba5a-8b0838030418


