// file for making requests to endpoints
GET http://localhost:3000/api/books/

###

POST http://localhost:3000/api/books
Content-Type: application/json

{
    "name": "test",
    "pages": 500
}

###

PUT http://localhost:3000/api/books/1
Content-Type: application/json

{
    "name": "Erikk",
    "pages": 450
}

###

DELETE http://localhost:3000/api/books/1


