// file for making requests to endpoints
GET http://localhost:3000/api/books/
###

POST http://localhost:3000/api/books
Content-Type: application/json

{
    "name": "testar",
    "pages": 50
}

###

PUT http://localhost:3000/api/books/
Content-Type: application/json

{
    "name": "Erikk",
    "pages": 450
}

###

DELETE http://localhost:3000/api/books/3552c4d0-051d-11ec-ba29-7f5fc216cdeb


